app/website/__init__.py
from flask import Blueprint

website = Blueprint('website', __name__)

from . import views

app/website/views.py
from . import website
from flask import render_template
from flask_login import login_required
from sqlalchemy import desc
from app.admin.utils import distribute_points_win_loss_draw
from app.models import Team, Match


@login_required
@website.route("/painel")
def dashboard():
    matches = Match.query.all()
    distribute_points_win_loss_draw(matches)
    teams = Team.query.order_by(desc(Team.points)).all()
    return render_template("website/dashboard.html", teams=teams)


@website.route("/")
def index():
    return render_template("website/home.html", title="Bem vindo!")


@website.route("/detalhes/<int:id>")
def details(id):
    team = Team.query.filter_by(id=id).first_or_404()
    matches_home_team = Match.query.filter_by(home_team=team.name).all()
    matches_guest_team = Match.query.filter_by(guest_team=team.name).all()
    for match in matches_guest_team:
        matches_home_team.append(match)
    return render_template("website/details.html", matches=matches_home_team)


app/templates/website/dashboard.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Times{% endblock %}
{% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <h1 style="text-align:center;">Times</h1>
        {% if teams %}
          <hr class="intro-divider">
          <div class="center">
            <table id="tabela" class="display table table-striped table-bordered"">
              <thead class="thead-dark">
                <tr>
                  <th> ID </th>
                  <th> Nome </th>
                  <th> Acrônimo </th>
                  <th> Local </th>
                  <th> Vitórias </th>
                  <th> Derrotas </th>
                  <th> Empate </th>
                  <th> Pontuação </th>
                  <th> + Info </th>
                </tr>
              </thead>
              <tbody>
              {% for team in teams %}
                <tr>
                  <td> {{ team.id }} </td>
                  <td> {{ team.name }} </td>
                  <td> {{ team.acronym }} </td>
                  <td> {{ team.local }} </td>
                  <td> {{ team.victories }} </td>
                  <td> {{ team.losses }} </td>
                  <td> {{ team.draws }} </td>
                  <td> {{ team.points }} </td>
                  <td>
                    <a href="{{ url_for('website.details', id=team.id) }}">
                      <i class="fa fa-plus"></i> Info
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
          <div style="text-align: center">
        {% else %}
          <div style="text-align: center">
            <h3> Nenhum time cadastrado. </h3>
            <hr class="intro-divider">
        {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/website/details.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Partidas{% endblock %}
{% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <h1 style="text-align:center;">Partidas</h1>
        {% if matches %}
          <hr class="intro-divider">
          <div class="center">
            <table id="tabela" class="display table table-striped table-bordered"">
              <thead class="thead-dark">
                <tr>
                  <th> ID </th>
                  <th> Time da casa </th>
                  <th> Time visitante </th>
                  <th> Placar da casa </th>
                  <th> Placar do visitante </th>
                </tr>
              </thead>
              <tbody>
              {% for match in matches %}
                <tr>
                  <td> {{ match.id }} </td>
                  <td> {{ match.home_team }} </td>
                  <td> {{ match.guest_team }} </td>
                  <td> {{ match.home_points }} </td>
                  <td> {{ match.guest_points }} </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
          <div style="text-align: center">
        {% else %}
          <div style="text-align: center">
            <h3> Nenhuma partida cadastrada. </h3>
            <hr class="intro-divider">
        {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/website/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>FlaskScoreBoard</h1>
                    <h3>Acompanhe seu time!</h3>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
body {
  background: url('static/img/intro-bg.jpg') no-repeat center center fixed;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  background-size: cover;
  -o-background-size: cover;
  background-color:rgba(0, 0, 0, 0.1);
}
</style>
{% endblock %}